dataset:
  cityscapes:
    batch_size: 8
    crop_size: 768
    epochs: 216
    eval_freq: 4
    im_size: 1024
    learning_rate: 0.01
    window_size: 768
    window_stride: 512
  flair1:
    batch_size: 8
    crop_size: 256
    data_path: /scratcht/FLAIR_1/train
    domains:
    - D060_2021
    - D070_2020
    - D017_2018
    - D074_2020
    - D044_2020
    - D049_2020
    - D058_2020
    - D021_2020
    - D014_2020
    - D081_2020
    n_channels : 3
    n_cls : 13
    epochs: 64
    eval_freq: 8
    im_size: 512
    learning_rate: 0.01
    seq_length: 10
    window_size: 256
    window_stride: 256
    classnames : {
        1 : "building", 
        2 : "pervious surface",
        3 : "impervious surface",
        4 : "bare soil",
        5 : "water",
        6 : "coniferous", 
        7 : "deciduous",
        8 : "brushwood", 
        9 : "vineyard", 
        10 : "herbaceous vegetation",
        11 : "agricultural land",
        12 : "plowed land",
        13 : "other"
        }
decoder:
  deeplab_dec:
    encoder_layer: -1
  linear: {}
  mask_transformer:
    drop_path_rate: 0.0
    dropout: 0.1
    n_layers: 2
model:
  vit_base_patch16_384:
    d_model: 768
    distilled: false
    image_size: 384
    n_heads: 12
    n_layers: 12
    normalization: vit
    patch_size: 16
  vit_base_patch32_384:
    d_model: 768
    image_size: 384
    n_heads: 12
    n_layers: 12
    normalization: vit
    patch_size: 32
  vit_base_patch8_384:
    d_model: 768
    distilled: false
    image_size: 384
    n_heads: 12
    n_layers: 12
    normalization: vit
    patch_size: 8
  vit_large_patch16_384:
    d_model: 1024
    image_size: 384
    n_heads: 16
    n_layers: 24
    normalization: vit
    patch_size: 16
  vit_large_patch32_384:
    d_model: 1024
    image_size: 384
    n_heads: 16
    n_layers: 24
    normalization: vit
    patch_size: 32
  vit_small_patch16_384:
    d_model: 384
    distilled: false
    image_size: 384
    n_heads: 6
    n_layers: 12
    normalization: vit
    patch_size: 16
  vit_small_patch32_384:
    d_model: 384
    distilled: false
    image_size: 384
    n_heads: 6
    n_layers: 12
    normalization: vit
    patch_size: 32
  vit_tiny_patch16_384:
    d_model: 192
    distilled: false
    image_size: 384
    n_heads: 3
    n_layers: 12
    normalization: vit
    patch_size: 16
seed: 4156
