wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/train.py
    python_version: 3.8.10
    cli_version: 0.16.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710515068.0
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 13
      - 15
      - 23
      4: 3.8.10
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
